version: "3.9"
services:
  funtastictoys-db:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: funtastictoys

  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - 8080:8080