version: "3.9"
services:
  funtastictoys-db:
    image: clokerul/funtastictoys
    build: ./database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: funtastictoys
    ports:
      - 5432:5432
    networks:
      - backend
      - database
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - 8080:8080
    networks:
      - database
    deploy:
      replicas: 1
      restart_policy:
          condition: on-failure
  
  auth:
    image: clokerul/backendinterface
    build: ./auth
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
    depends_on:
      - funtastictoys-db
    networks:
      - backend
    deploy:
      replicas: 3
      restart_policy:
          condition: on-failure

networks:
  frontend:
  backend:
    driver: overlay
  database: